# Generated by Django 5.2 on 2025-05-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espectador', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.palestrante')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('espectador', 'palestrante')},
            },
        ),
    ]
