# Generated by Django 5.2 on 2025-05-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espectador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='espectador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.espectador'),
        ),
    ]
